
import typing

from .part import Part



class AbaqusModel:
    name: str
    parts: typing.Dict[str, Part]

    def __init__(self, name: str):
        self.name = name

    def produce_inp_lines(self) -> typing.Iterable[str]:
        yield "*Heading"
        yield f"** Job name: Job-11 Model name: {self.name}"
        yield "** Generated by: Abaqus/CAE 2016"
        yield "*Preprint, echo=NO, model=NO, history=NO, contact=NO"
        yield "**"
        yield "** PARTS"
        yield "**"
        for part in self.parts.values():
            yield from part.produce_inp_lines()

